

default_platform(:android)

platform :android do
 desc "Lane For Android Firebase App Distribution"
 lane :firebase_distribution  do
  sh "flutter clean"
  sh "flutter build apk --release"
   firebase_app_distribution(
    app: "1:267243080219:android:2bb37f2d1b209523c346be",
    testers: "badrtest66@gmail.com",
    firebase_cli_token: "1//03NR3v_ZL_n8qCgYIARAAGAMSNwF-L9IrFvEjGiJmELp4iKlWvEj_ByJ6oY-MmocavdfMilouwNtnEKh_EX2AZWGw_25tcKyTmb8",
    android_artifact_type: "APK",
    android_artifact_path: "../build/app/outputs/flutter-apk/app-release.apk",
    release_notes: "first fastlane Firbase distribution new",
  )
 end


end
